# Generated by Django 3.0.8 on 2020-07-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0002_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='actual_value',
            field=models.PositiveSmallIntegerField(blank=True, default='unsold'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
